-----------------------------------------------------------------------------------------
--
-- HomeScene.lua
--
--Graphic Simulation of a Machine Learning Data Separator
--Project: Mobile App
--CSP2108 Introduction to Mobile Applcations Development 
-- Sem 2 2020
--By James Johnston - 10461776
-----------------------------------------------------------------------------------------